### ISSUE TITLE
KF5

### ISSUE THREAD

**Issue by grigorii-horos** [dschmidt/dolphin-plugin-owncloud#1]
Hi. You can update this plugin for KDE5 and KF5?

**Comment by dschmidt** [comment]
Doesnt the client support this out of the box by now? Otherwise yes I probably can.

@danimo ping

**Comment by grigorii-horos** [comment]
No, it client don't support. I use last version of ownCloud and Arch Linux.

**Comment by dschmidt** [comment]
Is it supported upstream by the client by now?

**Comment by grigorii-horos** [comment]
@dschmidt Yes

**Comment by danimo** [comment]
@dschmidt Yes, the client ship with a KF5/Dolphin plugin which has feature-parity with the other integrations.

**Comment by dschmidt** [comment]
Perfect. Fixed by waiting, lovely.
